# Generated by Django 4.1.2 on 2022-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('domesticBoxOffice', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Movie Domestic Box Office Data',
                'db_table': 'movie_data',
            },
        ),
    ]
